services:
  - type: web
    name: audio-deepfake-detector
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --timeout 120 --bind 0.0.0.0:$PORT app.server:app
    envVars:
      - key: GROQ_API_KEY
        sync: false