"""
server.py — backend for the custom UI.

Adds: a plain-English explanation of the evidence, generated by Groq if
GROQ_API_KEY is set in the environment, falling back to a deterministic
rule-based explanation otherwise (so the app always works, with or without
an API key, and never silently hangs mid-demo).

Run:
    python app/server.py
then open http://localhost:5000
"""
import os
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parent.parent))

import librosa
import numpy as np
import requests
import tempfile
import torch
from flask import Flask, jsonify, render_template, request

from src.features import N_BANDS, SAMPLE_RATE, extract_melspectrogram, load_audio
from src.rl_finetune import EvidenceClassifier, EvidencePolicy, explain

app = Flask(__name__)

CKPT_DIR = Path(__file__).resolve().parent.parent / "checkpoints" / "stage2"
N_MELS = 64

_mel_freqs = librosa.mel_frequencies(n_mels=N_MELS, fmax=SAMPLE_RATE / 2)
_band_edges = np.linspace(0, N_MELS, N_BANDS + 1).astype(int)
BAND_LABELS = [
    f"{int(_mel_freqs[_band_edges[i]])}\u2013{int(_mel_freqs[min(_band_edges[i + 1], N_MELS - 1)])} Hz"
    for i in range(N_BANDS)
]

# Plain-English meaning of each band, used by the rule-based explanation and
# handed to the LLM as context when the AI explanation path is used.
BAND_MEANINGS = [
    "natural pitch and prosody \u2014 the rise and fall of a voice",
    "the first vowel formant, tied to how natural vowels sound",
    "lower-mid vowel structure and clarity",
    "upper vowel formants and consonant transitions",
    "overall speech clarity \u2014 synthetic voices sometimes sound slightly too clean here",
    "sibilance and consonant detail (s, sh sounds)",
    "high-frequency texture, where vocoder artifacts often show up as unnatural smoothness",
    "breathiness and fine noise texture, which is hard for synthesis models to reproduce",
]

_classifier, _policy = None, None


def get_models():
    global _classifier, _policy
    if _classifier is None:
        classifier_path = CKPT_DIR / "evidence_classifier.pt"
        policy_path = CKPT_DIR / "evidence_policy.pt"
        if classifier_path.exists() and policy_path.exists():
            c = EvidenceClassifier()
            c.load_state_dict(torch.load(classifier_path, map_location="cpu"))
            c.eval()
            p = EvidencePolicy()
            p.load_state_dict(torch.load(policy_path, map_location="cpu"))
            p.eval()
            _classifier, _policy = c, p
    return _classifier, _policy


def generate_rule_based_explanation(prediction, confidence, band_labels, band_probs, evidence_bands):
    kept_idx = [i for i, k in enumerate(evidence_bands) if k]
    if not kept_idx:
        kept_idx = [int(np.argmax(band_probs))]
    top = sorted(kept_idx, key=lambda i: band_probs[i], reverse=True)[:2]
    band_text = " and ".join(f"the {band_labels[i]} range ({BAND_MEANINGS[i]})" for i in top)
    pct = round(confidence * 100)

    if prediction == "bonafide":
        return (
            f"This clip reads as bona fide with {pct}% confidence. The model leaned mainly on "
            f"{band_text} \u2014 these showed the kind of natural variation that's hard for "
            f"synthetic speech to fully replicate."
        )
    return (
        f"This clip is flagged as synthetic with {pct}% confidence. The giveaway shows up in "
        f"{band_text} \u2014 patterns that are common in AI-generated or voice-converted speech."
    )


def generate_explanation(prediction, confidence, band_labels, band_probs, evidence_bands):
    """Tries Groq first (if GROQ_API_KEY is set); always falls back to the
    deterministic explanation on any failure — missing key, no internet,
    rate limit, whatever — so a live demo never breaks on this step."""
    rule_based = generate_rule_based_explanation(
        prediction, confidence, band_labels, band_probs, evidence_bands
    )

    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        return rule_based, "rule-based"

    evidence_lines = "\n".join(
        f"- {label} ({BAND_MEANINGS[i]}): flagged={bool(kept)}, model weight={prob:.2f}"
        for i, (label, prob, kept) in enumerate(zip(band_labels, band_probs, evidence_bands))
    )
    prompt = (
        f"An audio deepfake detector analyzed a clip and predicted: {prediction} "
        f"({confidence*100:.0f}% confidence). Per-frequency-band evidence:\n{evidence_lines}\n\n"
        "In 2-3 plain-English sentences, explain what this means to a non-technical listener "
        "and why the flagged frequency ranges matter for spotting synthetic speech. No jargon "
        "without a plain explanation attached. Be concise and confident."
    )
    try:
        resp = requests.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            json={
                "model": os.environ.get("GROQ_MODEL", "llama-3.3-70b-versatile"),
                "max_tokens": 1500,
                "messages": [{"role": "user", "content": prompt}],
            },
            timeout=15,
        )
        if not resp.ok:
            # show the API's own error message, not just the status code
            print(f"[explain] Groq API returned {resp.status_code}: {resp.text[:300]}")
        else:
            text = resp.json()["choices"][0]["message"]["content"].strip()
            if text:
                return text, "ai"
    except Exception as e:
        print(f"[explain] Groq API call failed, falling back to rule-based explanation: {e}")

    return rule_based, "rule-based"


@app.route("/")
def index():
    return render_template("index.html")


@app.route("/api/predict", methods=["POST"])
def predict():
    if "file" not in request.files:
        return jsonify({"error": "No file uploaded."}), 400
    f = request.files["file"]
    tmp_path = os.path.join(tempfile.gettempdir(), "uploaded_clip")
    f.save(tmp_path)

    try:
        wav = load_audio(tmp_path)
    except Exception as e:
        return jsonify({"error": f"Could not read that audio file: {e}"}), 400

    classifier, policy = get_models()
    if classifier is None:
        return (
            jsonify(
                {
                    "error": "Stage 2 checkpoints not found. Run "
                    "`python -m src.rl_finetune train_classifier` and "
                    "`train_policy` first, then restart the server."
                }
            ),
            503,
        )

    result = explain(wav, classifier, policy)
    prediction = "bonafide" if result["prediction"] == "real" else "synthetic"

    explanation, explanation_source = generate_explanation(
        prediction, result["confidence"], BAND_LABELS, result["band_keep_probs"], result["evidence_bands"]
    )

    log_mel = extract_melspectrogram(wav, n_mels=N_MELS)
    waveform_preview = wav[:: max(1, len(wav) // 600)].tolist()

    return jsonify(
        {
            "prediction": prediction,
            "confidence": result["confidence"],
            "evidence_bands": result["evidence_bands"],
            "band_keep_probs": result["band_keep_probs"],
            "band_labels": BAND_LABELS,
            "spectrogram": log_mel.tolist(),
            "waveform": waveform_preview,
            "explanation": explanation,
            "explanation_source": explanation_source,
        }
    )


if __name__ == "__main__":
    app.run(debug=True, port=5000)
# Replace the last line:
if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)