"""
server.py — backend for the custom UI.

Detection uses a two-tier approach:
  1. Primary verdict: Stage 1 SSL classifier (Wav2Vec2 + attention-pool head),
     loaded from checkpoints/stage1/best_model.pt. This is the accurate model.
  2. Evidence display: Stage 2 RL evidence policy, loaded from
     checkpoints/stage2/. Shows which frequency bands were flagged.

If Stage 1 checkpoint is missing, falls back to Stage 2 only.

Explanation is generated by Groq if GROQ_API_KEY is set in the environment,
falling back to a deterministic rule-based explanation otherwise.

Run:
    python app/server.py
then open http://localhost:5000
"""
import os
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parent.parent))

import librosa
import numpy as np
import requests
import tempfile
import torch
from flask import Flask, jsonify, render_template, request

from src.features import N_BANDS, SAMPLE_RATE, extract_melspectrogram, load_audio
from src.rl_finetune import EvidenceClassifier, EvidencePolicy, explain

app = Flask(__name__)

CKPT_DIR      = Path(__file__).resolve().parent.parent / "checkpoints" / "stage2"
STAGE1_CKPT   = Path(__file__).resolve().parent.parent / "checkpoints" / "stage1" / "best_model.pt"
N_MELS = 64

_mel_freqs  = librosa.mel_frequencies(n_mels=N_MELS, fmax=SAMPLE_RATE / 2)
_band_edges = np.linspace(0, N_MELS, N_BANDS + 1).astype(int)
BAND_LABELS = [
    f"{int(_mel_freqs[_band_edges[i]])}–{int(_mel_freqs[min(_band_edges[i + 1], N_MELS - 1)])} Hz"
    for i in range(N_BANDS)
]

BAND_MEANINGS = [
    "natural pitch and prosody — the rise and fall of a voice",
    "the first vowel formant, tied to how natural vowels sound",
    "lower-mid vowel structure and clarity",
    "upper vowel formants and consonant transitions",
    "overall speech clarity — synthetic voices sometimes sound slightly too clean here",
    "sibilance and consonant detail (s, sh sounds)",
    "high-frequency texture, where vocoder artifacts often show up as unnatural smoothness",
    "breathiness and fine noise texture, which is hard for synthesis models to reproduce",
]

# ── Model caches ──────────────────────────────────────────────────────────────
_ssl_classifier = None   # Stage 1 — Wav2Vec2 + attention head (primary verdict)
_classifier     = None   # Stage 2 — evidence MLP (evidence display only)
_policy         = None   # Stage 2 — RL policy (evidence display only)


def get_ssl_model():
    """Load the Stage 1 Wav2Vec2 classifier (accurate, used for the verdict)."""
    global _ssl_classifier
    if _ssl_classifier is not None:
        return _ssl_classifier
    if not STAGE1_CKPT.exists():
        print("[server] Stage 1 checkpoint not found — will use Stage 2 fallback.")
        return None
    try:
        from src.ssl_classifier import SSLClassifier
        print("[server] Loading Stage 1 SSL model (this may take a moment)…")
        model = SSLClassifier(freeze_encoder=True)
        state = torch.load(str(STAGE1_CKPT), map_location="cpu")
        model.load_state_dict(state)
        model.eval()
        _ssl_classifier = model
        print("[server] Stage 1 SSL model loaded.")
    except Exception as e:
        print(f"[server] Could not load Stage 1 model: {e}")
        _ssl_classifier = None
    return _ssl_classifier


def get_stage2_models():
    """Load Stage 2 evidence models (used for frequency band visualization)."""
    global _classifier, _policy
    if _classifier is None:
        classifier_path = CKPT_DIR / "evidence_classifier.pt"
        policy_path     = CKPT_DIR / "evidence_policy.pt"
        if classifier_path.exists() and policy_path.exists():
            c = EvidenceClassifier()
            c.load_state_dict(torch.load(str(classifier_path), map_location="cpu"))
            c.eval()
            p = EvidencePolicy()
            p.load_state_dict(torch.load(str(policy_path), map_location="cpu"))
            p.eval()
            _classifier, _policy = c, p
    return _classifier, _policy


# ── Preload both models at startup (avoids 60s timeout on first request) ──────
print("[server] Preloading models at startup…")
get_ssl_model()
get_stage2_models()
print("[server] Models ready.")


def predict_with_ssl(wav: np.ndarray):
    """
    Run the Stage 1 Wav2Vec2 classifier.
    Returns (prediction, confidence) or None if unavailable.
    """
    model = get_ssl_model()
    if model is None:
        return None
    try:
        waveform = torch.tensor(wav, dtype=torch.float32).unsqueeze(0)  # (1, T)
        with torch.no_grad():
            logits, _ = model(waveform)
            probs = torch.softmax(logits, dim=1)[0]
        # Class 0 = bona fide, Class 1 = spoof (matches ASVspoof label convention)
        fake_prob = float(probs[1])
        prediction = "synthetic" if fake_prob > 0.5 else "bonafide"
        confidence = float(probs.max())
        return prediction, confidence
    except Exception as e:
        print(f"[server] SSL prediction failed: {e}")
        return None


# ── Explanation helpers ───────────────────────────────────────────────────────

def generate_rule_based_explanation(prediction, confidence, band_labels, band_probs, evidence_bands):
    kept_idx = [i for i, k in enumerate(evidence_bands) if k]
    if not kept_idx:
        kept_idx = [int(np.argmax(band_probs))]
    top = sorted(kept_idx, key=lambda i: band_probs[i], reverse=True)[:2]
    band_text = " and ".join(f"the {band_labels[i]} range ({BAND_MEANINGS[i]})" for i in top)
    pct = round(confidence * 100)

    if prediction == "bonafide":
        return (
            f"This clip reads as bona fide with {pct}% confidence. The model leaned mainly on "
            f"{band_text} — these showed the kind of natural variation that's hard for "
            f"synthetic speech to fully replicate."
        )
    return (
        f"This clip is flagged as synthetic with {pct}% confidence. The giveaway shows up in "
        f"{band_text} — patterns that are common in AI-generated or voice-converted speech."
    )


def generate_explanation(prediction, confidence, band_labels, band_probs, evidence_bands):
    rule_based = generate_rule_based_explanation(
        prediction, confidence, band_labels, band_probs, evidence_bands
    )
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        return rule_based, "rule-based"

    evidence_lines = "\n".join(
        f"- {label} ({BAND_MEANINGS[i]}): flagged={bool(kept)}, model weight={prob:.2f}"
        for i, (label, prob, kept) in enumerate(zip(band_labels, band_probs, evidence_bands))
    )
    prompt = (
        f"An audio deepfake detector analyzed a clip and predicted: {prediction} "
        f"({confidence*100:.0f}% confidence). Per-frequency-band evidence:\n{evidence_lines}\n\n"
        "In 2-3 plain-English sentences, explain what this means to a non-technical listener "
        "and why the flagged frequency ranges matter for spotting synthetic speech. No jargon "
        "without a plain explanation attached. Be concise and confident."
    )
    try:
        resp = requests.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            json={
                "model": os.environ.get("GROQ_MODEL", "llama-3.3-70b-versatile"),
                "max_tokens": 1500,
                "messages": [{"role": "user", "content": prompt}],
            },
            timeout=15,
        )
        if resp.ok:
            text = resp.json()["choices"][0]["message"]["content"].strip()
            if text:
                return text, "ai"
        else:
            print(f"[explain] Groq API returned {resp.status_code}: {resp.text[:300]}")
    except Exception as e:
        print(f"[explain] Groq API call failed, falling back: {e}")

    return rule_based, "rule-based"


# ── Routes ────────────────────────────────────────────────────────────────────

@app.route("/")
def index():
    return render_template("index.html")


@app.route("/api/predict", methods=["POST"])
def predict():
    if "file" not in request.files:
        return jsonify({"error": "No file uploaded."}), 400
    f = request.files["file"]
    tmp_path = os.path.join(tempfile.gettempdir(), "uploaded_clip")
    f.save(tmp_path)

    try:
        wav = load_audio(tmp_path)
    except Exception as e:
        return jsonify({"error": f"Could not read that audio file: {e}"}), 400

    # ── Step 1: Get the verdict from Stage 1 (accurate Wav2Vec2 model) ────────
    ssl_result = predict_with_ssl(wav)

    # ── Step 2: Get frequency-band evidence from Stage 2 (visualization) ──────
    classifier, policy = get_stage2_models()
    if classifier is None:
        return (
            jsonify({
                "error": "No model checkpoints found. Please ensure "
                         "checkpoints/stage1/ or checkpoints/stage2/ exist."
            }),
            503,
        )

    evidence_result = explain(wav, classifier, policy)

    # ── Step 3: Combine — Stage 1 verdict wins if available ───────────────────
    if ssl_result is not None:
        prediction, confidence = ssl_result
    else:
        # Fall back to Stage 2 verdict
        prediction = "bonafide" if evidence_result["prediction"] == "real" else "synthetic"
        confidence = evidence_result["confidence"]

    explanation, explanation_source = generate_explanation(
        prediction, confidence, BAND_LABELS,
        evidence_result["band_keep_probs"],
        evidence_result["evidence_bands"],
    )

    log_mel          = extract_melspectrogram(wav, n_mels=N_MELS)
    waveform_preview = wav[:: max(1, len(wav) // 600)].tolist()

    return jsonify({
        "prediction":          prediction,
        "confidence":          confidence,
        "evidence_bands":      evidence_result["evidence_bands"],
        "band_keep_probs":     evidence_result["band_keep_probs"],
        "band_labels":         BAND_LABELS,
        "spectrogram":         log_mel.tolist(),
        "waveform":            waveform_preview,
        "explanation":         explanation,
        "explanation_source":  explanation_source,
    })


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=False)